version: '3'

services:
  ganbaruby:
    image: ghcr.io/windyakin/ganbaruby:latest
    build: .
    env_file: .env
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
